apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: firmware-documentation
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: production
  owner: firmware-team