apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: firmware-docs
  title: Firmware Documentation
  description: Documentação destinada aos desenvolvedores da Diel Energia.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - documentation
spec:
  type: website
  lifecycle: production
  owner: firmware-team
  domain: firmware