site_name: Firmware Documentation
site_description: Documentação destinada aos desenvolvedores da Diel Energia.
site_author: Diel Team

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

nav:
  - Home: index.md
  - DAM:
    - Overview: dam/overview.md
    - Status: dam/status.md
    - Config: dam/config.md
    - Update: dam/update.md
  - DUT:
    - Overview: dut/overview.md
    - Execution: dut/execution.md
    - Results: dut/results.md
    - Config: dut/config.md
  - DAC:
    - Overview: dac/overview.md
    - Auth: dac/auth.md
    - Permissions: dac/permissions.md
    - Log: dac/log.md

plugins:
  - search
  - mkdocs-material
  - mkdocstrings
  - mkdocs-jupyter 